from tkinter.ttk import Notebook
from json import load
from customtkinter import *
#-------Dictionaries------
Months = ["January","February","March","April","May","June","July","August","September","October","November","December"]
Days = ["1","2","3","4","5","6","7","8","9","15","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"]   
#------TOPLEVEL------
with open("Configs.json","r") as configs:
    cnf = load(configs)
def open1():
    TopLevel1 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel1.title("Veronica Decided to Die")
    TopLevel1.geometry("300x300")
    TitleLabel1 = CTkLabel(master=TopLevel1,text="Veronica Decided to Die",text_color="#f8acff",fg_color="black",font=("Pacifico",20)).pack()
    AuthorLabel1 = CTkLabel(master=TopLevel1,text="Author : Paulo Coleho")
    AuthorLabel1.configure(cnf["books_info_labels_body"])
    AuthorLabel1.pack()
    PagesLabel1 = CTkLabel(master=TopLevel1,text="240 Pages")
    PagesLabel1.configure(cnf["books_info_labels_body"])
    PagesLabel1.pack()
    LanguageLabel1 = CTkLabel(master=TopLevel1,text="Language : English")
    LanguageLabel1.configure(cnf["books_info_labels_body"])
    LanguageLabel1.pack()
    PublisherLabel1 = CTkLabel(master=TopLevel1,text="Publisher : HarperOn")
    PublisherLabel1.configure(cnf["books_info_labels_body"])
    PublisherLabel1.pack()
    PriceLabel1 = CTkLabel(master=TopLevel1,text="Price : $7.21")
    PriceLabel1.configure(cnf["books_info_labels_body"])
    PriceLabel1.pack()
    
    TopLevel1.config(background="black")
    TopLevel1.mainloop()
def open2():
    TopLevel2 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel2.title("Midnight Library")
    TopLevel2.geometry("300x300")
    TitleLabel2 = CTkLabel(master=TopLevel2,text="Midnight Library",text_color="#c6f8ff",fg_color="black",font=("Pacifico",20)).pack()
    AuthorLabel2 = CTkLabel(master=TopLevel2,text="Author : Matt Haig")
    AuthorLabel2.configure(cnf["books_info_labels_body"])
    AuthorLabel2.pack()
    PagesLabel2 = CTkLabel(master=TopLevel2,text="340 Pages")
    PagesLabel2.configure(cnf["books_info_labels_body"])
    PagesLabel2.pack()
    LanguageLabel2 = CTkLabel(master=TopLevel2,text="Language : English")
    LanguageLabel2.configure(cnf["books_info_labels_body"])
    LanguageLabel2.pack()
    PublisherLabel2 = CTkLabel(master=TopLevel2,text="Publisher : Penguin Books")
    PublisherLabel2.configure(cnf["books_info_labels_body"])
    PublisherLabel2.pack()
    PriceLabel2 = CTkLabel(master=TopLevel2,text="Price : $12")
    PriceLabel2.configure(cnf["books_info_labels_body"])
    PriceLabel2.pack()

    TopLevel2.config(background="black")
    TopLevel2.mainloop()
def open3():
    TopLevel3 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel3.title("The both die at the end")
    TopLevel3.geometry("300x300")
    TitleLabel3 = CTkLabel(master=TopLevel3,text="The both die at the end",text_color="#cbff49",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel3 = CTkLabel(master=TopLevel3,text="Author : Adam Silver")
    AuthorLabel3.configure(cnf["books_info_labels_body"])
    AuthorLabel3.pack()
    PagesLabel3 = CTkLabel(master=TopLevel3,text="416 pages")
    PagesLabel3.configure(cnf["books_info_labels_body"])
    PagesLabel3.pack()
    LanguageLabel3 = CTkLabel(master=TopLevel3,text="Language : English")
    LanguageLabel3.configure(cnf["books_info_labels_body"])
    LanguageLabel3.pack()
    PublisherLabel3 = CTkLabel(master=TopLevel3,text="Publisher : Quill Tree Books")
    PublisherLabel3.configure(cnf["books_info_labels_body"])
    PublisherLabel3.pack()
    PriceLabel3 = CTkLabel(master=TopLevel3,text="Price : $11.99")
    PriceLabel3.configure(cnf["books_info_labels_body"])
    PriceLabel3.pack()

    TopLevel3.config(background="black")
    TopLevel3.mainloop()
def open4():
    TopLevel4 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel4.title("Magic Shop")
    TopLevel4.geometry("300x300")
    TitleLabel4 = CTkLabel(master=TopLevel4,text="Magic Shop",text_color="#fa9372",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel4 = CTkLabel(master=TopLevel4,text="Author : James R Dotty")
    AuthorLabel4.configure(cnf["books_info_labels_body"])
    AuthorLabel4.pack()
    PagesLabel4 = CTkLabel(master=TopLevel4,text="288 pages")
    PagesLabel4.configure(cnf["books_info_labels_body"])
    PagesLabel4.pack()
    LanguageLabel4 = CTkLabel(master=TopLevel4,text="Language : English")
    LanguageLabel4.configure(cnf["books_info_labels_body"])
    LanguageLabel4.pack()
    PublisherLabel4 = CTkLabel(master=TopLevel4,text="Publisher : Avery")
    PublisherLabel4.configure(cnf["books_info_labels_body"])
    PublisherLabel4.pack()
    PriceLabel4 = CTkLabel(master=TopLevel4,text="Price : $9.99")
    PriceLabel4.configure(cnf["books_info_labels_body"])
    PriceLabel4.pack()
    TopLevel4.config(background="black")
    TopLevel4.mainloop()
def open5():
    TopLevel5 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel5.title("The Suicide Shop")
    TopLevel5.geometry("300x300")
    TitleLabel5 = CTkLabel(master=TopLevel5,text="The Suicide Shop",text_color="#bf0fff",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel5 = CTkLabel(master=TopLevel5,text="Author : Jean Teule")
    AuthorLabel5.configure(cnf["books_info_labels_body"])
    AuthorLabel5.pack()
    PagesLabel5 = CTkLabel(master=TopLevel5,text="177 Pages")
    PagesLabel5.configure(cnf["books_info_labels_body"])
    PagesLabel5.pack()
    LanguageLabel5 = CTkLabel(master=TopLevel5,text="Language : English")
    LanguageLabel5.configure(cnf["books_info_labels_body"])
    LanguageLabel5.pack()
    PublisherLabel5 = CTkLabel(master=TopLevel5,text="Publisher : Gallic Books")
    PublisherLabel5.configure(cnf["books_info_labels_body"])
    PublisherLabel5.pack()
    PriceLabel5 = CTkLabel(master=TopLevel5,text="Price : $4.99")
    PriceLabel5.configure(cnf["books_info_labels_body"])
    PriceLabel5.pack()
    TopLevel5.config(background="black")
    TopLevel5.mainloop()   
    
def open6():
    TopLevel6 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel6.title("Shatter Me")
    TopLevel6.geometry("300x300")
    TitleLabel6 = CTkLabel(master=TopLevel6,text="Shatter Me",text_color="#c6f8ff",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel6 = CTkLabel(master=TopLevel6,text="Author : Tahereh Mafi")
    AuthorLabel6.configure(cnf["books_info_labels_body"])
    AuthorLabel6.pack()
    PagesLabel6 = CTkLabel(master=TopLevel6,text="1830 Pages")
    PagesLabel6.configure(cnf["books_info_labels_body"])
    PagesLabel6.pack()
    LanguageLabel6 = CTkLabel(master=TopLevel6,text="Language : English")
    LanguageLabel6.configure(cnf["books_info_labels_body"])
    LanguageLabel6.pack()
    PublisherLabel6 = CTkLabel(master=TopLevel6,text="Publisher : HarperCollins")
    PublisherLabel6.configure(cnf["books_info_labels_body"])
    PublisherLabel6.pack()
    PriceLabel6 = CTkLabel(master=TopLevel6,text="Price : $59.99")
    PriceLabel6.configure(cnf["books_info_labels_body"])
    PriceLabel6.pack()
    ShtterMeLabel = CTkLabel(master=TopLevel6,text="The Six-Novel Collection: Shatter Me, Unravel Me, Ignite Me, Restore Me, Defy Me, Imagine Me ",text_color="gray90",fg_color="black").pack()
    TopLevel6.config(background="black")
    TopLevel6.mainloop()
def open7():
    TopLevel7 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel7.title("Harry Potter")
    TopLevel7.geometry("300x300")
    TitleLabel7 = CTkLabel(master=TopLevel7,text="Harry Potter")
    TitleLabel7.configure(cnf["books_info_labels_body"])
    TitleLabel7.pack()
    AuthorLabel7 = CTkLabel(master=TopLevel7,text="Author : J.K Rowling")
    AuthorLabel7.configure(cnf["books_info_labels_body"])
    AuthorLabel7.pack()
    PagesLabel7 = CTkLabel(master=TopLevel7,text="")
    PagesLabel7.configure(cnf["books_info_labels_body"])
    PagesLabel7.pack()
    LanguageLabel7 = CTkLabel(master=TopLevel7,text="Language : English")
    LanguageLabel7.configure(cnf["books_info_label_body"])
    LanguageLabel7.pack()
    PublisherLabel7 = CTkLabel(master=TopLevel7,text="Publisher : Scholastic Inc")
    PagesLabel7.configure(cnf["books_info_labels_body"])
    PagesLabel7.pack()
    PriceLabel7 = CTkLabel(master=TopLevel7,text="Price : $62.99")
    PriceLabel7.configure(cnf["books_info_labels_body"])
    PriceLabel7.pack()
    TopLevel7.config(background="black")
    TopLevel7.mainloop()
def open8():
    TopLevel8 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel8.title("Never After")
    TopLevel8.geometry("300x300")
    TitleLabel8 = CTkLabel(master=TopLevel8,text="Never After",text_color="#cbff49",fg_color="black",font=("Pacifico",15)).pack()
    
    AuthorLabel8 = CTkLabel(master=TopLevel8,text="Author : ")
    AuthorLabel8.configure(cnf["books_info_labels_body"])
    AuthorLabel8.pack()
    PagesLabel8 = CTkLabel(master=TopLevel8,text="")
    PagesLabel8.configure(cnf["books_info_labels_body"])
    PagesLabel8.pack()
    LanguageLabel8 = CTkLabel(master=TopLevel8,text="Language : English")
    LanguageLabel8.configure(cnf["books_info_labels_body"])
    LanguageLabel8.pack()
    PublisherLabel8 = CTkLabel(master=TopLevel8,text="Publisher : ")
    PublisherLabel8.configure(cnf["books_info_labels_body"])
    PublisherLabel8.pack()
    PriceLabel8 = CTkLabel(master=TopLevel8,text="Price : ")
    PriceLabel8.configure(cnf["books_info_labels_body"])
    PriceLabel8.pack()
    TopLevel8.config(background="black")
    TopLevel8.mainloop()
def open9():
    TopLevel9 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel9.title("The Folk Of The Air")
    TopLevel9.geometry("300x300")
    TitleLabel9 = CTkLabel(master=TopLevel9,text="The Folk Of The Air",text_color="#fa9372",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel9 = CTkLabel(master=TopLevel9,text="Author : ")
    AuthorLabel9.configure(cnf["books_info_labels_body"])
    AuthorLabel9.pack()
    PagesLabel9 = CTkLabel(master=TopLevel9,text="")
    PagesLabel9.configure(cnf["books_info_labels_body"])
    PagesLabel9.pack()
    LanguageLabel9 = CTkLabel(master=TopLevel9,text="Language : English")
    LanguageLabel9.configure(cnf["books_info_labels_body"])
    LanguageLabel9.pack()
    PublisherLabel9 = CTkLabel(master=TopLevel9,text="Publisher : ")
    PublisherLabel9.configure(cnf["books_info_labels_body"])
    PublisherLabel9.pack()
    PriceLabel9 = CTkLabel(master=TopLevel9,text="Price : ")
    PriceLabel9.configure(cnf["books_info_labels_body"])
    PriceLabel9.pack()
    TopLevel9.config(background="black")
    TopLevel9.mainloop()   
def open10():
    TopLevel10 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel10.title("The 100")
    TopLevel10.geometry("300x300")
    TitleLabel10 = CTkLabel(master=TopLevel10,text="The 100",text_color="#bf0fff",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel10 = CTkLabel(master=TopLevel10,text="Author : ")
    AuthorLabel10.configure(cnf["books_info_labels_body"])
    AuthorLabel10.pack()
    PagesLabel10 = CTkLabel(master=TopLevel10,text="")
    PagesLabel10.configure(cnf["books_info_labels_body"])
    PagesLabel10.pack()
    LanguageLabel10 = CTkLabel(master=TopLevel10,text="Language : English")
    LanguageLabel10.configure(cnf["books_info_labels_body"])
    LanguageLabel10.pack()
    PublisherLabel10 = CTkLabel(master=TopLevel10,text="Publisher : ")
    PublisherLabel10.configure(cnf["books_info_labels_body"])
    PublisherLabel10.pack()
    PriceLabel10 = CTkLabel(master=TopLevel10,text="Price : ")
    PriceLabel10.configure(cnf["books_info_labels_body"])
    PriceLabel10.pack()
    TopLevel10.config(background="black")
    TopLevel10.mainloop()
def open11():
    TopLevel11 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel11.title("Reminders Of Him")
    TopLevel11.geometry("300x300")
    TitleLabel11 = CTkLabel(master=TopLevel11,text="Reminders Of Him",text_color="#f8acff",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel11 = CTkLabel(master=TopLevel11,text="Author : Coleen Hover")
    AuthorLabel11.configure(cnf["books_info_labels_body"])
    AuthorLabel11.pack()
    PagesLabel11 = CTkLabel(master=TopLevel11,text="335 pages")
    PagesLabel11.configure(cnf["books_info_labels_body"])
    PagesLabel11.pack()
    LanguageLabel11 = CTkLabel(master=TopLevel11,text="Language : English")
    LanguageLabel11.configure(cnf["books_info_labels_body"])
    LanguageLabel11.pack()
    PublisherLabel11 = CTkLabel(master=TopLevel11,text="Publisher : Montlake")
    PublisherLabel11.configure(cnf["books_info_labels_body"])
    PublisherLabel11.pack()
    PriceLabel11 = CTkLabel(master=TopLevel11,text="Price : $9")
    PriceLabel11.configure()
    PriceLabel11.pack()
    TopLevel11.config(background="black")
    TopLevel11.mainloop()
def open12():
    TopLevel12 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel12.title("It Ends With Us")
    TopLevel12.geometry("300x300")
    TitleLabel12 = CTkLabel(master=TopLevel12,text="It Ends With Us",text_color="#c6f8ff",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel12 = CTkLabel(master=TopLevel12,text="Author : Coleen Hover")
    AuthorLabel12.configure(cnf["books_info_labels_body"])
    AuthorLabel12.pack()
    PagesLabel12 = CTkLabel(master=TopLevel12,text="384 pages")
    PagesLabel12.configure(cnf["books_info_labels_body"])
    PagesLabel12.pack()
    LanguageLabel12 = CTkLabel(master=TopLevel12,text="Language : English")
    LanguageLabel12.configure(cnf["books_info_labels_body"])
    LanguageLabel12.pack()
    PublisherLabel12 = CTkLabel(master=TopLevel12,text="Publisher : Atria Books")
    PublisherLabel12.configure(cnf["books_info_labels_body"])
    PublisherLabel12.pack()
    PriceLabel12 = CTkLabel(master=TopLevel12,text="Price : $11.99")
    PriceLabel12.configure(cnf["books_info_labels_body"])
    PriceLabel12.pack()
    TopLevel12.config(background="black")        
    TopLevel12.mainloop()  
def open13():
    TopLevel13 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel13.title("Everything Everything")
    TopLevel13.geometry("300x300")
    TitleLabel13 = CTkLabel(master=TopLevel13,text="Everything Everything",text_color="#c6f8ff",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel13 = CTkLabel(master=TopLevel13,text="Author : Nicola Yon")
    AuthorLabel13.configure(cnf["books_info_labels_body"])
    AuthorLabel13.pack()
    PagesLabel13 = CTkLabel(master=TopLevel13,text="300 Pages")
    PagesLabel13.configure(cnf["books_info_labels_body"])
    PagesLabel13.pack()
    LanguageLabel13 = CTkLabel(master=TopLevel13,text="Language : English")
    LanguageLabel13.configure(cnf["books_info_labels_body"])
    LanguageLabel13.pack()
    PublisherLabel13 = CTkLabel(master=TopLevel13,text="Publisher : Listening Library")
    PublisherLabel13.configure(cnf["books_info_labels_body"])
    PublisherLabel13.pack()
    PriceLabel13 = CTkLabel(master=TopLevel13,text="Price : $8.99")
    PriceLabel13.configure(cnf["books_info_labels_body"])
    PriceLabel13.pack()
    TopLevel13.config(background="black")        
    TopLevel13.mainloop()  
def open14():
    TopLevel14 = CTkToplevel(master=LibraryFrame,bd=20)   
    TopLevel14.title("Looking For Alaska")
    TopLevel14.geometry("300x300")
    TitleLabel14 = CTkLabel(master=TopLevel14,text="Looking For Alaska",text_color="#fa9372",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel14 = CTkLabel(master=TopLevel14,text="Author : John Green")
    AuthorLabel14.configure(cnf["books_info_labels_body"])
    AuthorLabel14.pack()
    PagesLabel14 = CTkLabel(master=TopLevel14,text="297 Pages")
    PagesLabel14.configure(cnf["books_info_labels_body"])
    PagesLabel14.pack()
    LanguageLabel14 = CTkLabel(master=TopLevel14,text="Language : English")
    LanguageLabel14.configure(cnf["books_info_labels_body"])
    LanguageLabel14.pack()
    PublisherLabel14 = CTkLabel(master=TopLevel14,text="Publisher : Listening Library")
    PublisherLabel14.configure(cnf["books_info_labels_body"])
    PublisherLabel14.pack()
    PriceLabel14 = CTkLabel(master=TopLevel14,text="Price : $8.99")
    PriceLabel14.configure(cnf["books_info_labels_body"])
    PriceLabel14.pack()
    TopLevel14.config(background="black")     
    TopLevel14.mainloop()  
def open15():
    TopLevel15 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel15.title("November 9")
    TopLevel15.geometry("300x300")
    TitleLabel15 = CTkLabel(master=TopLevel15,text="November 9",text_color="#bf0fff",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel15 = CTkLabel(master=TopLevel15,text="Author : Coleen Hover")
    AuthorLabel15.configure(cnf["books_info_labels_body"])
    AuthorLabel15.pack()
    PagesLabel15 = CTkLabel(master=TopLevel15,text="320 pages")
    PagesLabel15.configure(cnf["books_info_labels_body"])
    PagesLabel15.pack()
    LanguageLabel15 = CTkLabel(master=TopLevel15,text="Language : English")
    LanguageLabel15.configure(cnf["books_info_labels_body"])
    LanguageLabel15.pack()
    PublisherLabel15 = CTkLabel(master=TopLevel15,text="Publisher : Atria Books")
    PublisherLabel15.configure(cnf["books_info_labels_body"])
    PublisherLabel15.pack()
    PriceLabel15 = CTkLabel(master=TopLevel15,text="Price : $12.99")
    PriceLabel15.configure(cnf["books_info_labels_body"])
    PriceLabel15.pack()
    TopLevel15.config(background="black")        
    TopLevel15.mainloop() 
def open16():
    TopLevel16 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel16.title("The Guest List")
    TopLevel16.geometry("300x300")
    TitleLabel16 = CTkLabel(master=TopLevel16,text="The Guest List",text_color="#f8acff",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel16 = CTkLabel(master=TopLevel16,text="Author : Lucy Foley")
    AuthorLabel16.configure(cnf["books_info_labels_body"])
    AuthorLabel16.pack()
    PagesLabel16 = CTkLabel(master=TopLevel16,text="384 Pages")
    PagesLabel16.configure(cnf["books_info_labels_body"])
    PagesLabel16.pack()
    LanguageLabel16 = CTkLabel(master=TopLevel16,text="Language : English")
    LanguageLabel16.configure(cnf["books_info_labels_body"])
    LanguageLabel16.pack()
    PublisherLabel16 = CTkLabel(master=TopLevel16,text="Publisher : Harper")
    PublisherLabel16.configure(cnf["books_info_labels_body"])
    PublisherLabel16.pack()
    PriceLabel16 = CTkLabel(master=TopLevel16,text="Price : $11.99")
    PriceLabel16.configure(cnf["books_info_labels_body"])
    PriceLabel16.pack()
    TopLevel16.config(background="black")        
    TopLevel16.mainloop() 
def open17():
    TopLevel17 = CTkToplevel(master=LibraryFrame,bd=20)
    TopLevel17.title("One Of Us Is Lying")
    TopLevel17.geometry("300x300")
    TitleLabel17 = CTkLabel(master=TopLevel17,text="One Of Us Is Lying",text_color="#c6f8ff",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel17 = CTkLabel(master=TopLevel17,text="Author : Karen M. McManus")
    AuthorLabel17.configure(cnf["books_info_labels_body"])
    AuthorLabel17.pack()
    PagesLabel17 = CTkLabel(master=TopLevel17,text="416 pages")
    PagesLabel17.configure(cnf["books_info_labels_body"])
    PagesLabel17.pack()
    LanguageLabel17 = CTkLabel(master=TopLevel17,text="Language : English")
    LanguageLabel17.configure(cnf["books_info_labels_body"])
    LanguageLabel17.pack()
    PublisherLabel17 = CTkLabel(master=TopLevel17,text="Publisher : Delacorte Press")
    PublisherLabel17.configuren(cnf["books_info_labels_body"])
    PublisherLabel17.pack()
    PriceLabel17 = CTkLabel(master=TopLevel17,text="Price : $8.99")
    PriceLabel17.configure(cnf["books_info_labels_body"])
    PriceLabel17.pack()
    TopLevel17.config(background="black")        
    TopLevel17.mainloop() 
def open18():
    TopLevel18 = CTkToplevel(master=LibraryFrame,bd=20) 
    TopLevel18.title("Whats Become Of Her")
    TopLevel18.geometry("300x300")
    TitleLabel18 = CTkLabel(master=TopLevel18,text="Whats Become Of Her",text_color="#c6f8ff",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel18 = CTkLabel(master=TopLevel18,text="Author : Abe Clark")
    AuthorLabel18.configure(cnf["books_info_labels_body"])
    AuthorLabel18.pack()
    PagesLabel18 = CTkLabel(master=TopLevel18,text="397 pages")
    PagesLabel18.configure(cnf["books_info_labels_body"])
    PagesLabel18.pack()
    LanguageLabel18 = CTkLabel(master=TopLevel18,text="Language : English")
    LanguageLabel18.configure(cnf["books_info-labels_body"])
    LanguageLabel18.pack()
    PublisherLabel18 = CTkLabel(master=TopLevel18,text="Publisher : Leeds Press Corp")
    PublisherLabel18.configure(cnf["books_info_labels_body"])
    PublisherLabel18.pack()
    PriceLabel18 = CTkLabel(master=TopLevel18,text="Price : $9.95")
    PriceLabel18.configure(cnf["books_info_labels_body"])
    PriceLabel18.pack()
    TopLevel18.config(background="black")       
    TopLevel18.mainloop() 
def open19():
    TopLevel19 = CTkToplevel(master=LibraryFrame,bd=20)  
    TopLevel19.title("Shadow Land")
    TopLevel19.geometry("300x300")
    TitleLabel19 = CTkLabel(master=TopLevel19,text="Shadow Land",text_color="#fa9372",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel19 = CTkLabel(master=TopLevel19,text="Author : ")
    AuthorLabel19.configure(["books_info_labels_body"])
    AuthorLabel19.pack()
    PagesLabel19 = CTkLabel(master=TopLevel19,text="596 Pages")
    PagesLabel19.configure(cnf["books_info_labels_body"])
    PagesLabel19.pack()
    LanguageLabel19 = CTkLabel(master=TopLevel19,text="Language : English")
    LanguageLabel19.configure(cnf["books_info_labels_body"])
    LanguageLabel19.pack()
    PublisherLabel19 = CTkLabel(master=TopLevel19,text="Publisher : ")
    PublisherLabel19.configure(cnf["books_info_labels_body"])
    PublisherLabel19.pack()
    PriceLabel19 = CTkLabel(master=TopLevel19,text="Price : $6.99")
    PriceLabel19.configure(cnf["books_info_labels_body"])
    PriceLabel19.pack()
    TopLevel19.config(background="black")      
    TopLevel19.mainloop() 
def open20():
    TopLevel20 = CTkToplevel(master=LibraryFrame,bd=20)  
    TopLevel20.title("Where The Crawdads Sing")
    TopLevel20.geometry("300x300")
    TitleLabel20 = CTkLabel(master=TopLevel20,text="Where The Crawdads Sing",text_color="#bf0fff",fg_color="black",font=("Pacifico",15)).pack()
    AuthorLabel20 = CTkLabel(master=TopLevel20,text="")
    AuthorLabel20.configure(cnf["books_info_labels_body"])
    AuthorLabel20.pack()
    PagesLabel20 = CTkLabel(master=TopLevel20,text="")
    PagesLabel20.configure(cnf["books_info_labels_body"])
    PagesLabel20.pack()
    LanguageLabel20 = CTkLabel(master=TopLevel20,text="Language : English")
    LanguageLabel20.configure(cnf["books_info_labels_body"])
    LanguageLabel20.pack()
    PublisherLabel20 = CTkLabel(master=TopLevel20,text="Publisher : ")
    PublisherLabel20.configure(cnf["books_info_labels_body"])
    PublisherLabel20.pack()
    PriceLabel20 = CTkLabel(master=TopLevel20,text="Price : $")
    PriceLabel20.configure(cnf["books_info_labels_body"])
    PriceLabel20.pack()
    TopLevel20.config(background="black")      
    TopLevel20.mainloop()                                              
#------NoteBook------
root = CTk()
root.title("Anna's Library")
root.configure(text_color="black")
Labyrinth = Notebook(master=root)
LogInFrame = CTkFrame(master=Labyrinth,width=400,height=400)
LibraryFrame =  CTkFrame(master=Labyrinth,width=400,height=400,border_width=10,border_color="Hot pink")
ReadinglistFrame = CTkFrame(master=Labyrinth,width=400,height=400)

Labyrinth.pack()
LogInFrame.pack()
LibraryFrame.pack()
ReadinglistFrame.pack()

LogInFrame.configure(fg_color="black")
LibraryFrame.configure(fg_color="black")
ReadinglistFrame.configure(fg_color="black")

Labyrinth.add(child=LogInFrame,text="LogIn")
Labyrinth.add(child=LibraryFrame,text="Library")
Labyrinth.add(child=ReadinglistFrame,text="Read Next")              
#-------Library-------
Heayy1 = CTkLabel(master=LibraryFrame,text="Veronica Decided To Die.",width=20,text_color="black",fg_color="#f8acff",font=("Teko",15)).grid(row=1,column=0,sticky="nsew")
Heayy2 = CTkLabel(master=LibraryFrame,text="Midnight Library",width=20,text_color="black",fg_color="#c6f8ff",font=("Teko",15)).grid(row=2,column=0,sticky="nsew")
Heayy3 = CTkLabel(master=LibraryFrame,text="The both die at the end",width=20,text_color="black",fg_color="#cbff49",font=("Teko",15)).grid(row=3,column=0,sticky="nsew")
Heayy4 = CTkLabel(master=LibraryFrame,text="Magic Shop",width=20,text_color="black",fg_color="#fa9372",font=("Teko",15)).grid(row=4,column=0,sticky="nsew")
Heayy5 = CTkLabel(master=LibraryFrame,text="The Suicide Shop",width=20,text_color="black",fg_color="#bf0fff",font=("Teko",15)).grid(row=5,column=0,sticky="nsew")
Heayy6 = CTkLabel(master=LibraryFrame,text="Shatter Me",width=20,text_color="black",fg_color="#f8acff",font=("Teko",15)).grid(row=1,column=2,sticky="nsew")
Heayy7 = CTkLabel(master=LibraryFrame,text="Harry Potter",width=20,text_color="black",fg_color="#c6f8ff",font=("Teko",15)).grid(row=2,column=2,sticky="nsew")
Heayy8 = CTkLabel(master=LibraryFrame,text="Never After",width=20,text_color="black",fg_color="#cbff49",font=("Teko",15)).grid(row=3,column=2,sticky="nsew")
Heayy9 = CTkLabel(master=LibraryFrame,text="The Folk of the Air",width=20,text_color="black",fg_color="#fa9372",font=("Teko",15)).grid(row=4,column=2,sticky="nsew")
Heayy10 = CTkLabel(master=LibraryFrame,text="The 100",width=20,text_color="black",fg_color="#bf0fff",font=("Teko",15)).grid(row=5,column=2,sticky="nsew")
Heayy11 = CTkLabel(master=LibraryFrame,text="Reminders Of him",width=20,text_color="black",fg_color="#f8acff",font=("Teko",15)).grid(row=7,column=0,sticky="nsew")
Heayy12 = CTkLabel(master=LibraryFrame,text="It ends with us",width=20,text_color="black",fg_color="#c6f8ff",font=("Teko",15)).grid(row=8,column=0,sticky="nsew")
Heayy13 = CTkLabel(master=LibraryFrame,text="Everything Everything",width=20,text_color="black",fg_color="#cbff49",font=("Teko",15)).grid(row=9,column=0,sticky="nsew")
Heayy14 = CTkLabel(master=LibraryFrame,text="Looking For Alaska",width=20,text_color="black",fg_color="#fa9372",font=("Teko",15)).grid(row=15,column=0,sticky="nsew")
Heayy15 = CTkLabel(master=LibraryFrame,text="November 9",width=20,text_color="black",fg_color="#bf0fff",font=("Teko",15)).grid(row=11,column=0,sticky="nsew")
Heayy16 = CTkLabel(master=LibraryFrame,text="The Guest List",width=20,text_color="black",fg_color="#f8acff",font=("Teko",15)).grid(row=7,column=2,sticky="nsew")
Heayy17 = CTkLabel(master=LibraryFrame,text="One of us is lying",width=20,text_color="black",fg_color="#c6f8ff",font=("Teko",15)).grid(row=8,column=2,sticky="nsew")
Heayy18 = CTkLabel(master=LibraryFrame,text="Whats become of her",width=20,text_color="black",fg_color="#cbff49",font=("Teko",15)).grid(row=9,column=2,sticky="nsew")
Heayy19 = CTkLabel(master=LibraryFrame,text="shadow land",width=20,text_color="black",fg_color="#fa9372",font=("Teko",15)).grid(row=15,column=2,sticky="nsew")
Heayy20 = CTkLabel(master=LibraryFrame,text="Where the clawdads sing",width=20,text_color="black",fg_color="#bf0fff",font=("Teko",15)).grid(row=11,column=2,sticky="nsew")
GenreLabel = CTkLabel(master=LibraryFrame,text="Psychological Fiction",width=24,fg_color="Black",text_color="gray90",font=("Teko",15)).grid(row=0,column=0,sticky="nsew")
GenreLabel1 = CTkLabel(master=LibraryFrame,text="Romance",width=24,fg_color="Black",text_color="gray90",font=("Teko",15)).grid(row=6,column=0,sticky="nsew")
GenreLabel2 = CTkLabel(master=LibraryFrame,text="Series",width=24,fg_color="Black",text_color="gray90",font=("Teko",15)).grid(row=0,column=2,sticky="nsew")
GenreLabel3 = CTkLabel(master=LibraryFrame,text="Mystery",width=24,fg_color="Black",text_color="gray90",font=("Teko",15)).grid(row=6,column=2,sticky="nsew")

Button1 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#f8acff",font=("Teko",12),border_width=2,border_color="#f8acff",command=open1).grid(row=1,column=1,sticky="nsew")
Button2 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#c6f8ff",font=("Teko",12),border_width=2,border_color="#c6f8ff",command=open2).grid(row=2,column=1,sticky="nsew")
Button3 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#cbff49",font=("Teko",12),border_width=2,border_color="#cbff49",command=open3).grid(row=3,column=1,sticky="nsew")
Button4 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#fa9372",font=("Teko",12),border_width=2,border_color="#fa9372",command=open4).grid(row=4,column=1,sticky="nsew")
Button5 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#bf0fff",font=("Teko",12),border_width=2,border_color="#bf0fff",command=open5).grid(row=5,column=1,sticky="nsew")
Button6 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#f8acff",font=("Teko",12),border_width=2,border_color="#f8acff",command=open6).grid(row=1,column=3,sticky="nsew")
Button7 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#c6f8ff",font=("Teko",12),border_width=2,border_color="#c6f8ff",command=open7).grid(row=2,column=3,sticky="nsew")
Button8 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#cbff49",font=("Teko",12),border_width=2,border_color="#cbff49",command=open8).grid(row=3,column=3,sticky="nsew")
Button9 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#fa9372",font=("Teko",12),border_width=2,border_color="#fa9372",command=open9).grid(row=4,column=3,sticky="nsew")
Button10 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#bf0fff",font=("Teko",12),border_width=2,border_color="#bf0fff",command=open10).grid(row=5,column=3,sticky="nsew")
Button11 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#f8acff",font=("Teko",12),border_width=2,border_color="#f8acff",command=open11).grid(row=7,column=1,sticky="nsew")
Button12 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#c6f8ff",font=("Teko",12),border_width=2,border_color="#c6f8ff",command=open12).grid(row=8,column=1,sticky="nsew")
Button13 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#cbff49",font=("Teko",12),border_width=2,border_color="#cbff49",command=open13).grid(row=9,column=1,sticky="nsew")
Button14 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#fa9372",font=("Teko",12),border_width=2,border_color="#fa9372",command=open14).grid(row=15,column=1,sticky="nsew")
Button15 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#bf0fff",font=("Teko",12),border_width=2,border_color="#bf0fff",command=open15).grid(row=11,column=1,sticky="nsew")
Button16 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#f8acff",font=("Teko",12),border_width=2,border_color="#f8acff",command=open16).grid(row=7,column=3,sticky="nsew")
Button17 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#c6f8ff",font=("Teko",12),border_width=2,border_color="#c6f8ff",command=open17).grid(row=8,column=3,sticky="nsew")
Button18 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#cbff49",font=("Teko",12),border_width=2,border_color="#cbff49",command=open18).grid(row=9,column=3,sticky="nsew")
Button19 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#fa9372",font=("Teko",12),border_width=2,border_color="#fa9372",command=open19).grid(row=15,column=3,sticky="nsew")
Button20 = CTkButton(master=LibraryFrame,text="See More!",width=15,fg_color="black",text_color="#bf0fff",font=("Teko",12),border_width=2,border_color="#bf0fff",command=open20).grid(row=11,column=3,sticky="nsew")
#-------LOGIN------
def Register():
    print("Accepted!")

def LogIn(): 
    print("Welcome Back!")

NameLabel = CTkLabel(master=LogInFrame,text="FullName:",text_color="#fa0ae6",fg_color="Black",width=22,font=("Teko",15))
UserNameLabel = CTkLabel(master=LogInFrame,text="Username:",text_color="#c6f8ff",fg_color="Black",width=22,font=("Teko",15))
PassWordLabel = CTkLabel(master=LogInFrame,text="Password:",text_color="#cbff49",fg_color="Black",width=22,font=("Teko",15))
AgeLabel = CTkLabel(master=LogInFrame,text="Age:",text_color="Black",fg_color="#ed8cda",width=22,font=("Teko",15))
MailLabel = CTkLabel(master=LogInFrame,text="E-Mail:",text_color="#fa9372",fg_color="Black",width=22,font=("Teko",15))
AddressLabel = CTkLabel(master=LogInFrame,text="Address:",text_color="#bf0fff",fg_color="Black",width=22,font=("Teko",15))
BirthMonthLabel = CTkLabel(master=LogInFrame,text="Birth Month:",text_color="#fff95b",fg_color="Black",width=22,font=("Teko",15))
BirthDayLabel = CTkLabel(master=LogInFrame,text="Birth Day:",text_color="#f5ccd4",fg_color="Black",width=22,font=("Teko",15))

NameValues = StringVar()
UserNameValues = StringVar()
PasswordValues = StringVar()
AddressValues = StringVar()
EmailValues = StringVar()
BirthDay = IntVar()
AgeValues = IntVar()


UserNameEntry = CTkEntry(master=LogInFrame,text_color="#c6f8ff",fg_color="black",width=16,textvariable=UserNameValues,border_width=2,border_color="#c6f8ff",font=("Playfair Display",15))
PassWordEntry = CTkEntry(master=LogInFrame,text_color="#cbff49",fg_color="black",width=16,textvariable=PasswordValues,border_width=2,border_color="#cbff49",font=("Playfair Display",15))
NameEntry = CTkEntry(master=LogInFrame,text_color="#fa0ae6",fg_color="black",width=16,textvariable=NameValues,border_width=2,border_color="#fa0ae6",font=("Playfair Display",15))
MailEntry = CTkEntry(master=LogInFrame,text_color="#fa9372",fg_color="black",width=16,textvariable=EmailValues,border_width=2,border_color="#fa9372",font=("Playfair Display",15))
AddressEntry = CTkEntry(master=LogInFrame,text_color="#bf0fff",fg_color="black",width=16,textvariable=AddressValues,border_width=2,border_color="#bf0fff",font=("Playfair Display",15))

LogInButton = CTkButton(master=LogInFrame,text="Log In",font=("Teko",15),fg_color="#ed8cda",text_color="black",border_width=3,border_color="#d902ae",command=LogIn)
RegisterButton = CTkButton(master=LogInFrame,text="Register",font=("Teko",15),fg_color="#b98efa",text_color="black",border_width=3,border_color="#4f04bf",command=Register)

Age1Checkbutton = CTkCheckBox(master=LogInFrame,text="5-15",text_color="#fa0ae6",fg_color="black",border_width=2,border_color="#fa0ae6",font=("Teko",15))
Age2CheckButton = CTkCheckBox(master=LogInFrame,text="15-14",text_color="#c6f8ff",fg_color="black",border_width=2,border_color="#c6f8ff",font=("Teko",15))
Age3CheckButton = CTkCheckBox(master=LogInFrame,text="15-18",text_color="#cbff49",fg_color="black",border_width=2,border_color="#cbff49",font=("Teko",15))
Age4CheckButton = CTkCheckBox(master=LogInFrame,text="18-24",text_color="#fa9372",fg_color="black",border_width=2,border_color="#fa9372",font=("Teko",15))
Age5CheckButton = CTkCheckBox(master=LogInFrame,text="+24",text_color="#bf0fff",fg_color="black",border_width=2,border_color="#bf0fff",font=("Teko",15))


LanguageLabel = CTkLabel(master=LogInFrame,text="Choose a language:",text_color="Black",fg_color="#b98efa",width=20,font=("Teko",15))
EnglishCheckbutton = CTkCheckBox(master=LogInFrame,text="English",fg_color="Black",text_color="#fa0ae6",border_width=2,border_color="#fa0ae6",font=("Teko",15))
PersianCheckButton = CTkCheckBox(master=LogInFrame,text="Persian",fg_color="Black",text_color="#c6f8ff",border_width=2,border_color="#c6f8ff",font=("Teko",15))
SpanishCheckButton = CTkCheckBox(master=LogInFrame,text="Spanish",fg_color="Black",text_color="#cbff49",border_width=2,border_color="#cbff49",font=("Teko",15))

MonthsCombobox = CTkComboBox(master=LogInFrame,width=27,values=Months)
DaysCombobox = CTkComboBox(master=LogInFrame,width=27,values=Days)

SigningSwitch = CTkSwitch(master=LogInFrame,text="Stay Signed In!",text_color="#8436f7").grid(row=8,column=0,sticky="nsew")

LanguageLabel.grid(row=0,column=3,sticky="nsew")
EnglishCheckbutton.grid(row=1,column=3,sticky="nsew")
PersianCheckButton.grid(row=2,column=3,sticky="nsew")
SpanishCheckButton.grid(row=3,column=3,sticky="nsew")


Age1Checkbutton.grid(row=1,column=2,sticky="nsew")
Age2CheckButton.grid(row=2,column=2,sticky="nsew")
Age3CheckButton.grid(row=3,column=2,sticky="nsew")
Age4CheckButton.grid(row=4,column=2,sticky="nsew")
Age5CheckButton.grid(row=5,column=2,sticky="nsew")

NameLabel.grid(row=0,column=0,sticky="nsew")
UserNameLabel.grid(row=1,column=0,sticky="nsew")
PassWordLabel.grid(row=2,column=0,sticky="nsew")
AgeLabel.grid(row=0,column=2,sticky="nsew")
MailLabel.grid(row=3,column=0,sticky="nsew")
AddressLabel.grid(row=5,column=0,sticky="nsew")
BirthMonthLabel.grid(row=4,column=0,sticky="nsew")
BirthDayLabel.grid(row=5,column=0,sticky="nsew")

NameEntry.grid(row=0,column=1,sticky="nsew")
UserNameEntry.grid(row=1,column=1,sticky="nsew")
PassWordEntry.grid(row=2,column=1,sticky="nsew")
MailEntry.grid(row=3,column=1,sticky="nsew")
AddressEntry.grid(row=4,column=1,sticky="nsew")


LogInButton.grid(row=6,column=0,sticky="nsew")
RegisterButton.grid(row=6,column=1,sticky="nsew")

MonthsCombobox.grid(row=4,column=1,sticky="nsew")
DaysCombobox.grid(row=5,column=1,sticky="nsew")

#------ReadingList-------
SardarLabel = CTkLabel(master=ReadinglistFrame,text="Keep your Next book here!",width=30,text_color="#fa0ae6",fg_color="black",font=("Teko",15)).grid(row=0,column=1,sticky="nsew")

EntryValues1 = StringVar()
EntryValues2 = StringVar()
EntryValues3 = StringVar()
EntryValues4 = StringVar()
EntryValues5 = StringVar()
EntryValues6 = StringVar()
EntryValues7 = StringVar()
EntryValues8 = StringVar()
EntryValues9 = StringVar()
EntryValues10 = StringVar()

CheckbuttonValues1 = IntVar()
CheckbuttonValues2 = IntVar()
CheckbuttonValues3 = IntVar()
CheckbuttonValues4 = IntVar()
CheckbuttonValues5 = IntVar()
CheckbuttonValues6 = IntVar()
CheckbuttonValues7 = IntVar()
CheckbuttonValues8 = IntVar()
CheckbuttonValues9 = IntVar()
CheckbuttonValues10 = IntVar()

Checkbutton1 = CTkCheckBox(master=ReadinglistFrame,text="1",fg_color="black",text_color="#f8acff",border_width=2,border_color="#fa0ae6",font=("Teko",15),textvariable=CheckbuttonValues1).grid(row=1,column=0,sticky="nsew")
Checkbutton2 = CTkCheckBox(master=ReadinglistFrame,text="2",fg_color="black",text_color="#c6f8ff",border_width=2,border_color="#c6f8ff",font=("Teko",15),textvariable=CheckbuttonValues2).grid(row=2,column=0,sticky="nsew")
Checkbutton3 = CTkCheckBox(master=ReadinglistFrame,text="3",fg_color="black",text_color="#cbff49",border_width=2,border_color="#cbff49",font=("Teko",15),textvariable=CheckbuttonValues3).grid(row=3,column=0,sticky="nsew")
Checkbutton4 = CTkCheckBox(master=ReadinglistFrame,text="4",fg_color="black",text_color="#fa9372",border_width=2,border_color="#fa9372",font=("Teko",15),textvariable=CheckbuttonValues4).grid(row=4,column=0,sticky="nsew")
Checkbutton5 = CTkCheckBox(master=ReadinglistFrame,text="5",fg_color="black",text_color="#bf0fff",border_width=2,border_color="#bf0fff",font=("Teko",15),textvariable=CheckbuttonValues5).grid(row=5,column=0,sticky="nsew")
Checkbutton6 = CTkCheckBox(master=ReadinglistFrame,text="6",fg_color="black",text_color="#f8acff",border_width=2,border_color="#fa0ae6",font=("Teko",15),textvariable=CheckbuttonValues6).grid(row=6,column=0,sticky="nsew")
Checkbutton7 = CTkCheckBox(master=ReadinglistFrame,text="7",fg_color="black",text_color="#c6f8ff",border_width=2,border_color="#c6f8ff",font=("Teko",15),textvariable=CheckbuttonValues7).grid(row=7,column=0,sticky="nsew")
Checkbutton8 = CTkCheckBox(master=ReadinglistFrame,text="8",fg_color="black",text_color="#cbff49",border_width=2,border_color="#cbff49",font=("Teko",15),textvariable=CheckbuttonValues8).grid(row=8,column=0,sticky="nsew")
Checkbutton9 = CTkCheckBox(master=ReadinglistFrame,text="9",fg_color="black",text_color="#fa9372",border_width=2,border_color="#fa9372",font=("Teko",15),textvariable=CheckbuttonValues9).grid(row=9,column=0,sticky="nsew")
Checkbutton10 = CTkCheckBox(master=ReadinglistFrame,text="10",fg_color="black",text_color="#bf0fff",border_width=2,border_color="#bf0fff",font=("Teko",15),textvariable=CheckbuttonValues10).grid(row=10,column=0,sticky="nsew")

Entry1 = CTkEntry(master=ReadinglistFrame,fg_color="black",text_color="#f8acff",width=20,border_width=2,border_color="#f8acff",textvariable=EntryValues1).grid(row=1,column=1,sticky="nsew")
Entry2 = CTkEntry(master=ReadinglistFrame,fg_color="black",text_color="#c6f8ff",width=20,border_width=2,border_color="#c6f8ff",textvariable=EntryValues2).grid(row=2,column=1,sticky="nsew")
Entry3 = CTkEntry(master=ReadinglistFrame,fg_color="black",text_color="#cbff49",width=20,border_width=2,border_color="#cbff49",textvariable=EntryValues3).grid(row=3,column=1,sticky="nsew")
Entry4 = CTkEntry(master=ReadinglistFrame,fg_color="black",text_color="#fa9372",width=20,border_width=2,border_color="#fa9372",textvariable=EntryValues4).grid(row=4,column=1,sticky="nsew")
Entry5 = CTkEntry(master=ReadinglistFrame,fg_color="black",text_color="#bf0fff",width=20,border_width=2,border_color="#bf0fff",textvariable=EntryValues5).grid(row=5,column=1,sticky="nsew")
Entry6 = CTkEntry(master=ReadinglistFrame,fg_color="black",text_color="#f8acff",width=20,border_width=2,border_color="#f8acff",textvariable=EntryValues6).grid(row=6,column=1,sticky="nsew")
Entry7 = CTkEntry(master=ReadinglistFrame,fg_color="black",text_color="#c6f8ff",width=20,border_width=2,border_color="#c6f8ff",textvariable=EntryValues7).grid(row=7,column=1,sticky="nsew")
Entry8 = CTkEntry(master=ReadinglistFrame,fg_color="black",text_color="#cbff49",width=20,border_width=2,border_color="#cbff49",textvariable=EntryValues8).grid(row=8,column=1,sticky="nsew")
Entry9 = CTkEntry(master=ReadinglistFrame,fg_color="black",text_color="#fa9372",width=20,border_width=2,border_color="#fa9372",textvariable=EntryValues9).grid(row=9,column=1,sticky="nsew")
Entry10 = CTkEntry(master=ReadinglistFrame,fg_color="black",text_color="#bf0fff",width=20,border_width=2,border_color="#bf0fff",textvariable=EntryValues10).grid(row=10,column=1,sticky="nsew")

SaveButton = CTkButton(master=ReadinglistFrame,text="Save",font=("Teko",15)).grid(row=11,column=1,sticky="nsew")

root.mainloop()
