from tkinter import Label,Button,Tk,Toplevel,StringVar
from time import sleep
game=Tk()
game.title("on bazie to windows 7")
game.config(bg="burlywood2")
game.geometry("128x68")
clr_list=[]
clr_list=["red","red","yellow","yellow","blue","blue","orange","orange","cyan","cyan","purple","purple","pink","pink","green","green"]
def third_pg():
    global second_page
    second_page=Toplevel()
    lbl=Label(second_page,text="enter timer")
    threes=Button(second_page,text="30 seconds",bg="maroon3",command=lambda:thirdh())
    twom=Button(second_page,text="2 minutes",bg="maroon3")
    fivem=Button(second_page,text="4 minute",bg="maroon3")
    threes.grid(row=2,column=1)
    twom.grid(row=2,column=2)
    fivem.grid(row=2,column=3)
    lbl.grid(row=1,column=2)
def forth_pg():
    second_page=Toplevel()
    lbl=Label(second_page,text="enter timer")
    threes=Button(second_page,text="30 seconds",bg="maroon3")
    twom=Button(second_page,text="2 minutes",bg="maroon3")
    fivem=Button(second_page,text="4 minute",bg="maroon3")
    threes.grid(row=2,column=1)
    twom.grid(row=2,column=2)
    fivem.grid(row=2,column=3)
    lbl.grid(row=1,column=2)
def sixth_pg():
    second_page=Toplevel()
    lbl=Label(second_page,text="enter timer")
    threes=Button(second_page,text="30 seconds",bg="maroon3")
    twom=Button(second_page,text="2 minutes",bg="maroon3")
    fivem=Button(second_page,text="4 minute",bg="maroon3")
    threes.grid(row=2,column=1)
    twom.grid(row=2,column=2)
    fivem.grid(row=2,column=3)
    lbl.grid(row=1,column=2)
label=Label(game,text="enter mode:",fg="white",bg="burlywood2")
labelez=Label(game,text="easy",fg="green",background="burlywood2")
labelmed=Label(game,text="medium",fg="yellow",background="burlywood2")
labelhard=Label(game,text="hard",fg="red",background="burlywood2")
third=Button(game,text="3x3",bg="burlywood3",command=lambda:third_pg())
forth=Button(game,text="4x4",bg="burlywood3",command=lambda:forth_pg())
sixth=Button(game,text="6x6",bg="burlywood3",command=lambda:sixth_pg())
label.grid(row=1,column=2)
labelez.grid(row=3,column=3)
labelmed.grid(row=3,column=2)
labelhard.grid(row=3,column=1)
forth.grid(row=2,column=2)
sixth.grid(row=2,column=1)
third.grid(row=2,column=3)
def thirdh():
    global second_page,sec_pg
    second_page.destroy()
    sec_pg=Toplevel()
    second= StringVar()
    minute= StringVar()
    But1=Button(sec_pg,width=9,height=3)
    But2=Button(sec_pg,width=9,height=3)
    But3=Button(sec_pg,width=9,height=3)
    But4=Button(sec_pg,width=9,height=3)
    But5=Button(sec_pg,width=9,height=3)
    But6=Button(sec_pg,width=9,height=3)
    But7=Button(sec_pg,width=9,height=3)
    But8=Button(sec_pg,width=9,height=3)
    But9=Button(sec_pg,width=9,height=3)
    mabel=Label(sec_pg,fg="black")
    mabel2=Label(sec_pg,text=":",fg="black")
    sabel=Label(sec_pg,fg="black")
    mabel.grid(row=0,column=4)
    mabel2.grid(row=0,column=5)
    sabel.grid(row=0,column=6)

    But1.grid(columnspan=3,sticky="news",row=1,column=1)
    But2.grid(columnspan=3,sticky="news",row=1,column=4)
    But3.grid(columnspan=3,sticky="news",row=1,column=7)
    But4.grid(columnspan=3,sticky="news",row=2,column=1)
    But5.grid(columnspan=3,sticky="news",row=2,column=4)
    But6.grid(columnspan=3,sticky="news",row=2,column=7)
    But7.grid(columnspan=3,sticky="news",row=3,column=1)
    But8.grid(columnspan=3,sticky="news",row=3,column=4)
    But9.grid(columnspan=3,sticky="news",row=3,column=7)
    def zaman(a):
     time=a
     mabel.config(textvariable=minute)
     sabel.config(textvariable=second)
     while time > -1:
      mins , sec = (time // 60 , time % 60)
      second.set(sec)
      minute.set(mins)
     sleep(0.001)
     game.update()
     if(time == 0):
         second.set('00')
         minute.set('00')
         sec_pg.destroy()
         score_pg=Toplevel()
         slabel=Label(score_pg,text="")
         dlabel=Label(score_pg,text="your score:")
         slabel.grid(row=1,column=1)
         dlabel.grid(row=1,column=2)
     time -= 1
    zaman(30)


game.mainloop()