# Built-In , Additional , 
from turtle import fd,rt,lt,done,pencolor,pensize,bgcolor,bgpic,speed,shapesize,penup,pendown,shape,setx,sety,circle
from time import sleep
# bgpic("SpyXFamily.jpg")
shape("turtle")
bgcolor("black")
pensize(width=10)
pencolor("red")
speed(1)
shapesize(5)
penup()
setx(90)
sety(100)
pendown()
penup()
fd(distance=400)
sleep(1)
lt(angle=120)
sleep(1)
pendown()
fd(distance=400)
sleep(1)
lt(angle=120)
sleep(1)
penup()
fd(distance=400)
sleep(1)
lt(angle=120)
sleep(1)
penup()
fd(distance=450)
sleep(1)
lt(angle=120)
sleep(1)
pendown()
fd(distance=450)
sleep(1)
lt(angle=120)
sleep(1)
penup()
fd(distance=450)
sleep(1)
lt(angle=120)
sleep(1)
pendown()
circle(radius=50 ,extent=270)
done()