from turtle import forward,left,right,back,circle,speed
from tkinter import Label,LabelFrame,Entry,Button,Tk
root= Tk()
root.title("HOW!?")
speed(5)
def jolo(): 
     a=int(range_ent.get())
     forward(a)
def aghab():
     a=int(range_ent.get())
     back(a)
def rast():
     a=int(range_ent.get())
     b=int(degree_ent.get())
     right(b)
     forward(a)
def chap():
     a=int(range_ent.get())
     b=int(degree_ent.get())
     left(b)
     forward(a)     


def roright():
     b=int(degree_ent.get())
     right(b)
def roleft():
     b=int(degree_ent.get())
     left(b)


def upmosalas():
     a=int(range_ent.get())
     forward(a/2)
     left(120)
     forward(a)
     left(120)
     forward(a)
     left(120)
     forward(a/2)
def downmosalas():
     a=int(range_ent.get())
     forward(a/2)
     right(120)
     forward(a)
     right(120)
     forward(a)
     right(120)
     forward(a/2)
def rightmosalas():
     a=int(range_ent.get())
     right(90)
     forward(a/2)
     left(120)
     forward(a)
     left(120)
     forward(a)
     left(120)
     forward(a/2)
     left(90)
def leftmosalas():
     a=int(range_ent.get())
     left(90)
     forward(a/2)
     left(120)
     forward(a)
     left(120)
     forward(a)
     left(120)
     forward(a/2)
     right(90)

def downmoraba():
     a=int(range_ent.get())
     forward(a/2)
     right(90)
     forward(a)
     right(90)
     forward(a)
     right(90)
     forward(a)
     right(90)
     forward(a/2)
def upmoraba():
     a=int(range_ent.get())
     forward(a/2)
     left(90)
     forward(a)
     left(90)
     forward(a)
     left(90)
     forward(a)
     left(90)
     forward(a/2)
def rightmoraba():
     a=int(range_ent.get())
     left(90)
     forward(a/2)
     right(90)
     forward(a)
     right(90)
     forward(a)
     right(90)
     forward(a)
     right(90)
     forward(a/2)
     right(90)
def leftmoraba():
     a=int(range_ent.get())
     right(90)
     forward(a/2)
     right(90)
     forward(a)
     right(90)
     forward(a)
     right(90)
     forward(a)
     right(90)
     forward(a/2)
     left(90)

def uphexagon():
     a=int(range_ent.get())
     left(30)
     forward(a)
     left(60)
     forward(a)
     left(60)
     forward(a)
     left(60)
     forward(a)
     left(60)
     forward(a)
     left(60)
     forward(a)
     left(30)
def downhexagon():
     a=int(range_ent.get())
     right(30)
     forward(a)
     right(60)
     forward(a)
     right(60)
     forward(a)
     right(60)
     forward(a)
     right(60)
     forward(a)
     right(60)
     forward(a)
     right(30)
def lefthexagon():
     a=int(range_ent.get())
     left(120)
     forward(a)
     left(60)
     forward(a)
     left(60)
     forward(a)
     left(60)
     forward(a)
     left(60)
     forward(a)
     left(60)
     forward(a)
     right(60)

def righthexagon():
     a=int(range_ent.get())
     right(60)
     forward(a)
     left(60)
     forward(a)
     left(60)
     forward(a)
     left(60)
     forward(a)
     left(60)
     forward(a)
     left(60)
     forward(a)
     left(120)

def upmostatil():
     a=int(range_ent.get())
     b=int(width_ent.get())
     forward(a/2)
     left(90)
     forward(b)
     left(90)
     forward(a)
     left(90)
     forward(b)
     left(90)
     forward(a/2)
def downmostatil():
     a=int(range_ent.get())
     b=int(width_ent.get())
     forward(a/2)
     right(90)
     forward(b)
     right(90)
     forward(a)
     right(90)
     forward(b)
     right(90)
     forward(a/2)     
def rightmostatil():
     a=int(range_ent.get())
     b=int(width_ent.get())    
     left(90)
     forward(a/2)
     right(90)
     forward(b)
     right(90)
     forward(a)
     right(90)
     forward(b)
     right(90)
     forward(a/2)
     right(90)
def leftmostatil():
     a=int(range_ent.get())
     b=int(width_ent.get())
     right(90)
     forward(a/2)
     right(90)
     forward(b)
     right(90)
     forward(a)
     right(90)
     forward(b)
     right(90)
     forward(a/2)
     left(90)

def updayere():
     a=int(range_ent.get())
     speed(10)
     circle(a)
     speed(5)
def downdayere():
     a=int(range_ent.get())
     speed(10)
     left(180)
     circle(a)
     left(180)
     speed(5)
def rightdayere():
     a=int(range_ent.get())
     speed(10)
     right(90)
     circle(a)
     right(270)
     speed(5)
def leftdayere():
     a=int(range_ent.get())
     speed(10)
     left(90)
     circle(a)
     left(270)
     speed(5)


#def degree():

control_fr=LabelFrame(root,text="control")
shape_fr=LabelFrame(root,text="shapes")
dayere_fr=LabelFrame(shape_fr,text="dayere")
mosalas_fr=LabelFrame(shape_fr,text="mosalas")
moraba_fr=LabelFrame(shape_fr,text="moraba")
mostatil_fr=LabelFrame(shape_fr,text="mostatil")
hexagon_fr=LabelFrame(shape_fr,text="shish zelei")
size_fr=LabelFrame(root,text="range")
rotate_fr=LabelFrame(root,text="rotate")

control_fr.grid(row=1,column=1,sticky="news")
shape_fr.grid(row=2,column=1,sticky="news",columnspan=11,rowspan=1)

rotate_fr.grid(row=1,column=2,columnspan=10)

mosalas_fr.grid(row=1,column=1,sticky="news",columnspan=2)
moraba_fr.grid(row=1,column=3,sticky="news",columnspan=2)
hexagon_fr.grid(row=1,column=5,sticky="news",columnspan=2)
mostatil_fr.grid(row=2,column=2,sticky="news",columnspan=2)
dayere_fr.grid(row=2,column=4,sticky="news",columnspan=2)

size_fr.grid(row=10,column=1,sticky="news",columnspan=11)

roright_btn=Button(rotate_fr,text="right",width=8,command=lambda:roright())
roleft_btn=Button(rotate_fr,text="left",width=8,command=lambda:roleft())
roright_btn.grid(row=1,column=14,sticky="news",columnspan=2)
roleft_btn.grid(row=1,column=12,sticky="news",columnspan=2)

forward_btn=Button(control_fr,text="forward",width=10,command=lambda:jolo())
back_btn=Button(control_fr,text="back",width=10,command=lambda:aghab())
right_btn=Button(control_fr,text="right",width=10,command=lambda:rast())
left_btn=Button(control_fr,text="left",width=10,command=lambda:chap())

forward_btn.grid(row=1,column=1,padx=10,pady=2,columnspan=3,sticky="news")
back_btn.grid(row=1,column=4,pady=2,padx=10,columnspan=3,sticky="news")
right_btn.grid(row=1,column=7,pady=2,padx=10,columnspan=3,sticky="news")
left_btn.grid(row=1,column=10,padx=10,pady=2,columnspan=3,sticky="news")
##########################
upmosalas_btn=Button(mosalas_fr,text="△",width=8,height=3,command=lambda:upmosalas())
downmosalas_btn=Button(mosalas_fr,text="▽",width=8,height=3,command=lambda:downmosalas())
rightmosalas_btn=Button(mosalas_fr,text="▷",width=8,height=3,command=lambda:rightmosalas())
leftmosalas_btn=Button(mosalas_fr,text="◁",width=8,height=3,command=lambda:leftmosalas())
#grid
upmosalas_btn.grid(row=1,column=3,sticky="news",columnspan=2,rowspan=2)
downmosalas_btn.grid(row=3,column=3,sticky="news",columnspan=2,rowspan=2)
rightmosalas_btn.grid(row=2,column=5,sticky="news",columnspan=2,rowspan=2)
leftmosalas_btn.grid(row=2,column=1,sticky="news",columnspan=2,rowspan=2)
########################### 
upmoraba_btn=Button(moraba_fr,text="◻",width=8,height=3,command=lambda:upmoraba())
downmoraba_btn=Button(moraba_fr,text="□",width=8,height=3,command=lambda:downmoraba())
rightmoraba_btn=Button(moraba_fr,text="◧",width=8,height=3,command=lambda:rightmoraba())
leftmoraba_btn=Button(moraba_fr,text="◨",width=8,height=3,command=lambda:leftmoraba())
#grid
upmoraba_btn.grid(row=1,column=7,sticky="news",columnspan=2,rowspan=2)
downmoraba_btn.grid(row=3,column=7,sticky="news",columnspan=2,rowspan=2)
rightmoraba_btn.grid(row=2,column=9,sticky="news",columnspan=2,rowspan=2)
leftmoraba_btn.grid(row=2,column=5,sticky="news",columnspan=2,rowspan=2)
###########################
upmostatil_btn=Button(mostatil_fr,text="▭",width=8,height=3,command=lambda:upmostatil())
downmostatil_btn=Button(mostatil_fr,text="▭",width=8,height=3,command=lambda:downmostatil())
rightmostatil_btn=Button(mostatil_fr,text="▯",width=8,height=3,command=lambda:rightmostatil())
leftmostatil_btn=Button(mostatil_fr,text="▯",width=8,height=3,command=lambda:leftmostatil())
#grid
upmostatil_btn.grid(row=4,column=3,sticky="news",columnspan=2,rowspan=2)
downmostatil_btn.grid(row=6,column=3,sticky="news",columnspan=2,rowspan=2)
rightmostatil_btn.grid(row=5,column=5,sticky="news",columnspan=2,rowspan=2)
leftmostatil_btn.grid(row=5,column=1,sticky="news",columnspan=2,rowspan=2)

updayere_btn=Button(dayere_fr,text="॰",width=8,height=3,command=lambda:updayere())
downdayere_btn=Button(dayere_fr,text="ₒ",width=8,height=3,command=lambda:downdayere())
rightdayere_btn=Button(dayere_fr,text="◐",width=8,height=3,command=lambda:rightdayere())
leftdayere_btn=Button(dayere_fr,text="◑",width=8,height=3,command=lambda:leftdayere())
#grid
updayere_btn.grid(row=4,column=7,sticky="news",columnspan=2,rowspan=2)
downdayere_btn.grid(row=6,column=7,sticky="news",columnspan=2,rowspan=2)
rightdayere_btn.grid(row=5,column=9,sticky="news",columnspan=2,rowspan=2)
leftdayere_btn.grid(row=5,column=5,sticky="news",columnspan=2,rowspan=2)
##########################
upshish_btn=Button(hexagon_fr,text="⬡",width=8,height=3,command=lambda:uphexagon())
downshish_btn=Button(hexagon_fr,text="⬡",width=8,height=3,command=lambda:downhexagon())
rightshish_btn=Button(hexagon_fr,text="⬣",width=8,height=3,command=lambda:righthexagon())
leftshish_btn=Button(hexagon_fr,text="⬣",width=8,height=3,command=lambda:lefthexagon())
#grid
upshish_btn.grid(row=1,column=3,sticky="news",columnspan=2,rowspan=2)
downshish_btn.grid(row=3,column=3,sticky="news",columnspan=2,rowspan=2)
rightshish_btn.grid(row=2,column=5,sticky="news",columnspan=2,rowspan=2)
leftshish_btn.grid(row=2,column=1,sticky="news",columnspan=2,rowspan=2)

#second page
range_ent=Entry(size_fr,width=23)
width_ent=Entry(size_fr,width=23)
degree_ent=Entry(size_fr,width=23)
rng_lbl=Label(size_fr,text="range:",fg="blue")
width_lbl=Label(size_fr,text="width(mostatil only):",fg="blue")
deg_lbl=Label(size_fr,text="degree:",fg="blue")
rng_lbl.grid(row=0,column=0)
deg_lbl.grid(row=0,column=2)
range_ent.grid(row=0,column=1)
degree_ent.grid(row=0,column=3)
width_ent.grid(row=0,column=5)
width_lbl.grid(row=0,column=4)
root.mainloop()