from tkinter import Tk,Label,Entry,Button,LabelFrame,messagebox,Text
from tkinter.ttk import Combobox,Spinbox
root=Tk()

#Keyboard has 61 buttons
#khat aval

esc=Button(root,text="Esc",height=2,width=4,relief="raised",border=5,bg="#F1F0E8")
esc.grid(row=1,column=1,columnspan=2,sticky="news")

manfiyek=Button(root,text="`",height=2,width=4,relief="raised",border=5)
manfiyek.grid(row=1,column=3,columnspan=2,sticky="news")

yek=Button(root,text="1",height=2,width=4,relief="raised",border=5)
yek.grid(row=1,column=5,columnspan=2,sticky="news")

do=Button(root,text="2",height=2,width=4,relief="raised",border=5)
do.grid(row=1,column=7,columnspan=2,sticky="news")

se=Button(root,text="3",height=2,width=4,relief="raised",border=5)
se.grid(row=1,column=9,columnspan=2,sticky="news")

char=Button(root,text="4",height=2,width=4,relief="raised",border=5)
char.grid(row=1,column=11,columnspan=2,sticky="news")

panj=Button(root,text="5",height=2,width=4,relief="raised",border=5)
panj.grid(row=1,column=13,columnspan=2,sticky="news")

shish=Button(root,text="6",height=2,width=4,relief="raised",border=5)
shish.grid(row=1,column=15,columnspan=2,sticky="news")

haft=Button(root,text="7",height=2,width=4,relief="raised",border=5)
haft.grid(row=1,column=17,columnspan=2,sticky="news")

hasht=Button(root,text="8",height=2,width=4,relief="raised",border=5)
hasht.grid(row=1,column=19,columnspan=2,sticky="news")

noh=Button(root,text="9",height=2,width=4,relief="raised",border=5)
noh.grid(row=1,column=21,columnspan=2,sticky="news")

sefr=Button(root,text="0",height=2,width=4,relief="raised",border=5)
sefr.grid(row=1,column=23,columnspan=2,sticky="news")

khat=Button(root,text="-",height=2,width=4,relief="raised",border=5)
khat.grid(row=1,column=25,columnspan=2,sticky="news")

mosavi=Button(root,text="=",height=2,width=4,relief="raised",border=5)
mosavi.grid(row=1,column=27,columnspan=2,sticky="news")

backespace=Button(root,text="⌫",height=2,width=4,relief="raised",border=5,bg="#F1F0E8")
backespace.grid(row=1,column=29,columnspan=2,sticky="news")

#khat dovom

tab=Button(root,text="Tab",height=2,width=8,relief="raised",border=5,bg="#F1F0E8")
tab.grid(row=2,column=1,columnspan=3,sticky="news")

q=Button(root,text="q",height=2,width=4,relief="raised",border=5,command=lambda:qq())
q.grid(row=2,column=4,columnspan=2,sticky="news")

w=Button(root,text="w",height=2,width=4,relief="raised",border=5,command=lambda:ww())
w.grid(row=2,column=6,columnspan=2,sticky="news")

e=Button(root,text="e",height=2,width=4,relief="raised",border=5,command=lambda:ee())
e.grid(row=2,column=8,columnspan=2,sticky="news")

r=Button(root,text="r",height=2,width=4,relief="raised",border=5)
r.grid(row=2,column=10,columnspan=2,sticky="news")

t=Button(root,text="t",height=2,width=4,relief="raised",border=5)
t.grid(row=2,column=12,columnspan=2,sticky="news")

y=Button(root,text="y",height=2,width=4,relief="raised",border=5)
y.grid(row=2,column=14,columnspan=2,sticky="news")

u=Button(root,text="u",height=2,width=4,relief="raised",border=5)
u.grid(row=2,column=16,columnspan=2,sticky="news")

i=Button(root,text="i",height=2,width=4,relief="raised",border=5)
i.grid(row=2,column=18,columnspan=2,sticky="news")

o=Button(root,text="o",height=2,width=4,relief="raised",border=5)
o.grid(row=2,column=20,columnspan=2,sticky="news")

p=Button(root,text="p",height=2,width=4,relief="raised",border=5)
p.grid(row=2,column=22,columnspan=2,sticky="news")

korushe=Button(root,text="[",height=2,width=4,relief="raised",border=5)
korushe.grid(row=2,column=24,columnspan=2,sticky="news")

bkorushe=Button(root,text="]",height=2,width=4,relief="raised",border=5)
bkorushe.grid(row=2,column=26,columnspan=2,sticky="news")

enter=Button(root,text="Enter",height=2,width=4,relief="raised",border=5,bg="#F1F0E8")
enter.grid(row=2,column=28,columnspan=3,sticky="news")
#khat sevom


caps1=Button(root,text="Caps",height=2,width=4,relief="raised",border=5,bg="#F1F0E8")
caps1.grid(row=3,column=1,columnspan=4,sticky="news")

a=Button(root,text="a",height=2,width=4,relief="raised",border=5)
a.grid(row=3,column=5,columnspan=2,sticky="news")

s=Button(root,text="s",height=2,width=4,relief="raised",border=5)
s.grid(row=3,column=7,columnspan=2,sticky="news")

d=Button(root,text="d",height=2,width=4,relief="raised",border=5)
d.grid(row=3,column=9,columnspan=2,sticky="news")

f=Button(root,text="f",height=2,width=4,relief="raised",border=5)
f.grid(row=3,column=11,columnspan=2,sticky="news")

g=Button(root,text="g",height=2,width=4,relief="raised",border=5)
g.grid(row=3,column=13,columnspan=2,sticky="news")

h=Button(root,text="h",height=2,width=4,relief="raised",border=5)
h.grid(row=3,column=15,columnspan=2,sticky="news")

j=Button(root,text="j",height=2,width=4,relief="raised",border=5)
j.grid(row=3,column=17,columnspan=2,sticky="news")

k=Button(root,text="k",height=2,width=4,relief="raised",border=5)
k.grid(row=3,column=19,columnspan=2,sticky="news")

l=Button(root,text="l",height=2,width=4,relief="raised",border=5)
l.grid(row=3,column=21,columnspan=2,sticky="news")

donoghte=Button(root,text=":",height=2,width=4,relief="raised",border=5)
donoghte.grid(row=3,column=23,columnspan=2,sticky="news")

potation=Button(root,text='"',height=2,width=4,relief="raised",border=5)
potation.grid(row=3,column=25,columnspan=2,sticky="news")

enter2=Button(root,text="↵",height=2,width=4,relief="raised",border=5,bg="#F1F0E8")
enter2.grid(row=3,column=27,columnspan=4,sticky="news")

#khat charom

shift1=Button(root,text="⇧ Shift",height=2,width=4,relief="raised",border=5,command=lambda:shift(),bg="#F1F0E8") 
shift1.grid(row=4,column=1,columnspan=5,sticky="news")

z=Button(root,text="z",height=2,width=4,relief="raised",border=5)
z.grid(row=4,column=6,columnspan=2,sticky="news")

x=Button(root,text="x",height=2,width=4,relief="raised",border=5)
x.grid(row=4,column=8,columnspan=2,sticky="news")

c=Button(root,text="c",height=2,width=4,relief="raised",border=5)
c.grid(row=4,column=10,columnspan=2,sticky="news")

v=Button(root,text="v",height=2,width=4,relief="raised",border=5)
v.grid(row=4,column=12,columnspan=2,sticky="news")

b=Button(root,text="b",height=2,width=4,relief="raised",border=5)
b.grid(row=4,column=14,columnspan=2,sticky="news")

n=Button(root,text="n",height=2,width=4,relief="raised",border=5)
n.grid(row=4,column=16,columnspan=2,sticky="news")

m=Button(root,text="m",height=2,width=4,relief="raised",border=5)
m.grid(row=4,column=18,columnspan=2,sticky="news")

virgol=Button(root,text=",",height=2,width=4,relief="raised",border=5)
virgol.grid(row=4,column=20,columnspan=2,sticky="news")

noghte=Button(root,text=".",height=2,width=4,relief="raised",border=5)
noghte.grid(row=4,column=22,columnspan=2,sticky="news")

slash=Button(root,text="/",height=2,width=4,relief="raised",border=5)
slash.grid(row=4,column=24,columnspan=2,sticky="news")

shift2=Button(root,text="⇧ Shift",height=2,width=4,relief="raised",border=5,command=lambda:shift(),bg="#F1F0E8")
shift2.grid(row=4,column=26,columnspan=5,sticky="news")

#kaht akhar

ctrl1=Button(root,text="Ctrl",height=2,width=4,relief="raised",border=5,bg="#F1F0E8")
ctrl1.grid(row=5,column=1,columnspan=3,sticky="news")

windows1=Button(root,text="Win",height=2,width=4,relief="raised",border=5,bg="#F1F0E8")
windows1.grid(row=5,column=4,columnspan=2,sticky="news")

alt1=Button(root,text="Alt",height=2,width=4,relief="raised",border=5,command=lambda:shiftalt(),bg="#F1F0E8")
alt1.grid(row=5,column=6,columnspan=3,sticky="news")

space=Button(root,text="Space",height=2,width=4,fg="dark grey",relief="raised",border=5,bg="#F1F0E8")
space.grid(row=5,column=9,columnspan=12,sticky="news")

alt2=Button(root,text="Alt",height=2,width=4,relief="raised",border=5,command=lambda:shiftalt(),bg="#F1F0E8")
alt2.grid(row=5,column=21,columnspan=3,sticky="news")

windows2=Button(root,text="Win",height=2,width=4,relief="raised",border=5,bg="#F1F0E8")
windows2.grid(row=5,column=24,columnspan=2,sticky="news")

fn=Button(root,text="""Made by
 Koosha""",height=2,width=4,fg="red",relief="raised",border=5,bg="#F1F0E8")
fn.grid(row=5,column=26,columnspan=2,sticky="news")

ctrl2=Button(root,text="Ctrl",height=2,width=4,relief="raised",border=5,activebackground="red",bg="#F1F0E8")
ctrl2.grid(row=5,column=28,columnspan=3,sticky="news")

komak=Text(root,height=3,relief="sunken",border=6,state="normal")
komak.grid(row=0,column=0,columnspan=32)
##############################    DEFS   ############################

def shift():
   es=q['text']
   if es=="q":
    alt1.config(bg="#FFDBC3")
    alt2.config(bg="#FFDBC3")
    shift1.config(fg="red",relief="raised")
    shift2.config(fg="red",relief="raised")
    manfiyek.config(text="~") 
    yek.config(text="!") 
    do.config(text="@") 
    se.config(text="#") 
    char.config(text="$") 
    panj.config(text="%") 
    shish.config(text="^") 
    haft.config(text="&") 
    hasht.config(text="*") 
    noh.config(text="(") 
    sefr.config(text=")") 
    mosavi.config(text="+") 
    khat.config(text="_") 
    q.config(text="Q") 
    w.config(text="W") 
    e.config(text="E") 
    r.config(text="R") 
    t.config(text="T") 
    y.config(text="Y") 
    u.config(text="U") 
    i.config(text="I") 
    o.config(text="O") 
    p.config(text="P") 
    korushe.config(text="{") 
    bkorushe.config(text="}") 
    a.config(text="A") 
    s.config(text="S")
    d.config(text="D") 
    f.config(text="F") 
    g.config(text="G") 
    h.config(text="H") 
    j.config(text="J") 
    k.config(text="K") 
    l.config(text="L") 
    donoghte.config(text=":") 
    potation.config(text='"') 
    z.config(text="Z") 
    x.config(text="X")
    c.config(text="C") 
    v.config(text="V") 
    b.config(text="B") 
    n.config(text="N") 
    m.config(text="M") 
    virgol.config(text="<") 
    noghte.config(text=">") 
    slash.config(text="?")     
   elif es=="Q":
    alt1.config(bg="#F1F0E8")
    alt2.config(bg="#F1F0E8")
    shift1.config(fg="black")
    shift2.config(fg="black")
    manfiyek.config(text="`") 
    yek.config(text="1") 
    do.config(text="2") 
    se.config(text="3") 
    char.config(text="4") 
    panj.config(text="5") 
    shish.config(text="6") 
    haft.config(text="7") 
    hasht.config(text="8") 
    noh.config(text="9") 
    sefr.config(text="0") 
    mosavi.config(text="=") 
    khat.config(text="-")    
    q.config(text="q") 
    w.config(text="w") 
    e.config(text="e") 
    r.config(text="r") 
    t.config(text="t") 
    y.config(text="y") 
    u.config(text="u") 
    i.config(text="i") 
    o.config(text="o") 
    p.config(text="p") 
    korushe.config(text="[") 
    bkorushe.config(text="]") 
    a.config(text="a") 
    s.config(text="s")
    d.config(text="d") 
    f.config(text="f") 
    g.config(text="g") 
    h.config(text="h") 
    j.config(text="j") 
    k.config(text="k") 
    l.config(text="l") 
    donoghte.config(text=";") 
    potation.config(text="'") 
    z.config(text="z") 
    x.config(text="x")
    c.config(text="c") 
    v.config(text="v") 
    b.config(text="b") 
    n.config(text="n") 
    m.config(text="m") 
    virgol.config(text=",") 
    noghte.config(text=".") 
    slash.config(text="/")
   elif es=="ض":
        shift1.config(fg="red",relief="raised")
        shift2.config(fg="red",relief="raised")
        alt1.config(bg="#FFDBC3")
        alt2.config(bg="#FFDBC3")
        shift1.config(fg="black",relief="raised")
        shift2.config(fg="black",relief="raised")
        manfiyek.config(text="×") 
        yek.config(text="!") 
        do.config(text="@") 
        se.config(text="#") 
        char.config(text="$") 
        panj.config(text="%") 
        shish.config(text="^")
        haft.config(text="&") 
        hasht.config(text="*") 
        noh.config(text=")") 
        sefr.config(text="(") 
        mosavi.config(text="+") 
        khat.config(text="_")
        q.config(text="ً") 
        w.config(text="ٌ") 
        e.config(text="ٍ") 
        r.config(text="ريال") 
        t.config(text="،") 
        y.config(text="؛") 
        u.config(text=",") 
        i.config(text="]") 
        o.config(text="[") 
        p.config(text="شششششششششششششششششششششش") 
        korushe.config(text="}") 
        bkorushe.config(text="{") 
        a.config(text="َ") 
        s.config(text="ُ")
        d.config(text="ِ") 
        f.config(text="ّ") 
        g.config(text="ۀ") 
        h.config(text="آ") 
        j.config(text="ـ") 
        k.config(text="«") 
        l.config(text="»") 
        donoghte.config(text=":") 
        potation.config(text='"') 
        z.config(text="ة") 
        x.config(text="ي")
        c.config(text="ژ") 
        v.config(text="ؤ") 
        b.config(text="إ") 
        n.config(text="أ") 
        m.config(text="ء") 
        virgol.config(text="<") 
        noghte.config(text=">") 
        slash.config(text="؟")       
   elif es=="ً":
        shift1.config(fg="black",relief="raised")
        shift2.config(fg="red",relief="raised")
        alt1.config(bg="#F1F0E8")
        alt2.config(bg="#F1F0E8")
        shift1.config(fg="black",relief="raised")
        shift2.config(fg="black",relief="raised")
        manfiyek.config(text="÷") 
        yek.config(text="1") 
        do.config(text="2") 
        se.config(text="3") 
        char.config(text="4") 
        panj.config(text="5") 
        shish.config(text="6")
        haft.config(text="7") 
        hasht.config(text="8") 
        noh.config(text="9") 
        sefr.config(text="0") 
        mosavi.config(text="=") 
        khat.config(text="-") 
        q.config(text="ض") 
        w.config(text="ص") 
        e.config(text="ث") 
        r.config(text="ق") 
        t.config(text="ف") 
        y.config(text="غ") 
        u.config(text="ع") 
        i.config(text="ه") 
        o.config(text="خ") 
        p.config(text="ح") 
        korushe.config(text="ج") 
        bkorushe.config(text="چ") 
        a.config(text="ش") 
        s.config(text="س")
        d.config(text="ی") 
        f.config(text="ب") 
        g.config(text="ل") 
        h.config(text="ا") 
        j.config(text="ت") 
        k.config(text="ن") 
        l.config(text="م") 
        donoghte.config(text="ک") 
        potation.config(text='گ') 
        z.config(text="ظ") 
        x.config(text="ط")
        c.config(text="ز") 
        v.config(text="ر") 
        b.config(text="ذ") 
        n.config(text="د") 
        m.config(text="ئ") 
        virgol.config(text="و") 
        noghte.config(text=".") 
        slash.config(text="/") 
def shiftalt():
   ed=q['text']
   if ed=="Q"or"ً" :
    if ed=="Q":
        alt1.config(bg="#F1F0E8")
        alt2.config(bg="#F1F0E8")
        shift1.config(fg="black",relief="raised")
        shift2.config(fg="black",relief="raised")
        manfiyek.config(text="÷") 
        yek.config(text="1") 
        do.config(text="2") 
        se.config(text="3") 
        char.config(text="4") 
        panj.config(text="5") 
        shish.config(text="6")
        haft.config(text="7") 
        hasht.config(text="8") 
        noh.config(text="9") 
        sefr.config(text="0") 
        mosavi.config(text="=") 
        khat.config(text="-") 
        q.config(text="ض") 
        w.config(text="ص") 
        e.config(text="ث") 
        r.config(text="ق") 
        t.config(text="ف") 
        y.config(text="غ") 
        u.config(text="ع") 
        i.config(text="ه") 
        o.config(text="خ") 
        p.config(text="ح") 
        korushe.config(text="ج") 
        bkorushe.config(text="چ") 
        a.config(text="ش") 
        s.config(text="س")
        d.config(text="ی") 
        f.config(text="ب") 
        g.config(text="ل") 
        h.config(text="ا") 
        j.config(text="ت") 
        k.config(text="ن") 
        l.config(text="م") 
        donoghte.config(text="ک") 
        potation.config(text='گ') 
        z.config(text="ظ") 
        x.config(text="ط")
        c.config(text="ز") 
        v.config(text="ر") 
        b.config(text="ذ") 
        n.config(text="د") 
        m.config(text="ئ") 
        virgol.config(text="و") 
        noghte.config(text=".") 
        slash.config(text="/") 
    elif ed=="ً":
        alt1.config(bg="#F1F0E8")
        alt2.config(bg="#F1F0E8")
        shift1.config(fg="black")
        shift2.config(fg="black")
        manfiyek.config(text="`") 
        yek.config(text="1") 
        do.config(text="2") 
        se.config(text="3") 
        char.config(text="4") 
        panj.config(text="5") 
        shish.config(text="6") 
        haft.config(text="7") 
        hasht.config(text="8") 
        noh.config(text="9") 
        sefr.config(text="0") 
        mosavi.config(text="=") 
        khat.config(text="-")    
        q.config(text="q") 
        w.config(text="w") 
        e.config(text="e") 
        r.config(text="r") 
        t.config(text="t") 
        y.config(text="y") 
        u.config(text="u") 
        i.config(text="i") 
        o.config(text="o") 
        p.config(text="p") 
        korushe.config(text="[") 
        bkorushe.config(text="]") 
        a.config(text="a") 
        s.config(text="s")
        d.config(text="d") 
        f.config(text="f") 
        g.config(text="g") 
        h.config(text="h") 
        j.config(text="j") 
        k.config(text="k") 
        l.config(text="l") 
        donoghte.config(text=";") 
        potation.config(text="'") 
        z.config(text="z") 
        x.config(text="x")
        c.config(text="c") 
        v.config(text="v") 
        b.config(text="b") 
        n.config(text="n") 
        m.config(text="m") 
        virgol.config(text=",") 
        noghte.config(text=".") 
        slash.config(text="/")  


root.mainloop()