user_number = int(input(">> "))
print(user_number ** 2)
user_number = int(input(">> "))
print(user_number ** 2)
user_number = int(input(">> "))
print(user_number ** 2)
user_number = int(input(">> "))
print(user_number ** 2)
user_number = int(input(">> "))
print(user_number ** 2)